name: SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call-workflow:
    uses: ricardotondello/shared-workflows/.github/workflows/code_quality.yml@master
    secrets:
      SONAR_TOKEN: {{ secrets.SONAR_TOKEN }}
      SONAR_PROJECTKEY: {{ secrets.SONAR_PROJECTKEY }}
      SONAR_ORGNAME: {{ secrets.SONAR_ORGNAME }}