name: "Deploy to NuGet"

on:
  push:
    tags:
    - 'v*'

jobs:
  call-workflow:
  uses: ricardotondello/shared-workflows/.github/workflows/nuget.yml@master
  secrets:
    NUGET_AUTH_TOKEN: {{ secrets.NUGET_AUTH_TOKEN }}